In [49]:
import numpy as np
x = np.array([1,5,2])
y = np.array([7,4,1])

In [2]:
#Vector Addition
z = x + y 

In [3]:
print(z)

[8 9 3]


In [51]:
dot = np.dot(x,y)

In [52]:
dot

29

In [8]:
#find arc cos
x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())
cos_angle  = dot / x_modulus/ y_modulus
angle = np.arccos(cos_angle)
print(angle)

0.860937724714


In [9]:
angle*180/np.pi

49.328098049712409

In [10]:
x * y

array([ 7, 20,  2])

In [59]:
# Do a Matrix product. 
y = np.matrix( ((1,2), (5, -1)) )
z = np.matrix( (1),(2))

TypeError: data type not understood

In [58]:
np.dot(y,z)

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [18]:
z * y

matrix([[11,  0]])

In [22]:
np.cross(y , z)

array([ 0, 11])

In [36]:
z = np.random.randn(4, 1)

In [37]:
y = np.random.randn(3,4)

In [38]:
zt = z.transpose()

In [39]:
zt

array([[ 1.06389432, -0.11794427, -0.55360834,  0.31501941]])

In [31]:
z1 = np.random.randn(3, 4)

In [40]:
y

array([[ 0.63120811,  0.94867067, -1.42083028, -0.58487248],
       [ 0.57007561,  0.31077258, -0.71151992, -0.19524274],
       [ 0.78128157, -0.12262114,  0.58543502, -0.0299932 ]])

In [43]:
for i in range(3):
    for j in range(4):
        x[i][j] = y[i][j] + z[j]

ValueError: setting an array element with a sequence.

In [44]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [45]:
c

array([[-0.87321492,  0.41119614, -0.98814762],
       [ 1.44685873,  0.71093175,  0.20287037]])

In [46]:
a

array([[-0.22430807,  1.06010299, -0.33924076],
       [ 1.02176398,  0.28583701, -0.22222438]])

In [47]:
b

array([[-0.64890685],
       [ 0.42509475]])